"""
src/regulatory/package.py

Phase 6: Regulatory Examination Package.

generate_regulatory_package() produces a self-contained JSON file that a
regulator can verify against the database independently without trusting
the system.

Package contents:
  1. Complete event stream for the application, in order, with full payloads
  2. State of every projection as it existed at examination_date
  3. Audit chain integrity verification result
  4. Human-readable narrative (one sentence per significant event)
     - Generated by Gemini 2.0 Flash if GEMINI_API_KEY is set
     - Falls back to template-based narrative otherwise
  5. Model versions, confidence scores, and input data hashes for every
     AI agent that participated
"""
from __future__ import annotations

import hashlib
import json
import logging
import os
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger(__name__)

# Events worth narrating (others are infrastructure noise)
NARRATIVE_EVENTS = {
    "ApplicationSubmitted",
    "CreditAnalysisRequested",
    "CreditAnalysisCompleted",
    "FraudScreeningCompleted",
    "ComplianceCheckRequested",
    "ComplianceRulePassed",
    "ComplianceRuleFailed",
    "ComplianceCheckCompleted",
    "DecisionGenerated",
    "HumanReviewCompleted",
    "ApplicationApproved",
    "ApplicationDeclined",
    "AuditIntegrityCheckRun",
}


@dataclass
class RegulatoryPackage:
    application_id:    str
    examination_date:  str
    generated_at:      str
    package_hash:      str    # SHA-256 of the entire package content (self-verifying)
    event_stream:      list[dict[str, Any]]
    projection_states: dict[str, Any]
    integrity_result:  dict[str, Any]
    narrative:         str
    agent_metadata:    list[dict[str, Any]]
    total_events:      int

    def to_dict(self) -> dict[str, Any]:
        return {
            "apex_regulatory_package_version": "1.0",
            "application_id":    self.application_id,
            "examination_date":  self.examination_date,
            "generated_at":      self.generated_at,
            "package_hash":      self.package_hash,
            "total_events":      self.total_events,
            "narrative":         self.narrative,
            "agent_metadata":    self.agent_metadata,
            "event_stream":      self.event_stream,
            "projection_states": self.projection_states,
            "integrity_result":  self.integrity_result,
        }


async def generate_regulatory_package(
    application_id: str,
    examination_date: datetime,
    store: Any,
    pool: Any,           # asyncpg.Pool
) -> RegulatoryPackage:
    """
    Generate a complete, self-contained regulatory examination package.
    The package can be verified independently against the database.
    """
    generated_at = datetime.now(timezone.utc).isoformat()
    exam_date_str = examination_date.isoformat()

    # ── 1. Complete event stream ───────────────────────────────────────────────
    loan_stream = f"loan-{application_id}"
    events = await store.load_stream(loan_stream)
    event_records = [
        {
            "stream_position": e.stream_position,
            "global_position": e.global_position,
            "event_type":      e.event_type,
            "event_version":   e.event_version,
            "payload":         e.payload,
            "metadata":        e.metadata,
            "recorded_at":     e.recorded_at.isoformat() if e.recorded_at else None,
        }
        for e in events
    ]

    # ── 2. Projection states at examination_date ───────────────────────────────
    projection_states: dict[str, Any] = {}
    async with pool.acquire() as conn:
        # ApplicationSummary — current state (no temporal query needed for this one)
        summary_row = await conn.fetchrow(
            "SELECT * FROM application_summary WHERE application_id = $1",
            application_id,
        )
        projection_states["application_summary"] = dict(summary_row) if summary_row else {}

        # ComplianceAuditView at examination_date
        from src.projections.compliance_audit import ComplianceAuditViewProjection
        compliance_state = await ComplianceAuditViewProjection.get_compliance_at(
            application_id, examination_date, conn
        )
        projection_states["compliance_audit_view"] = compliance_state.summary()

    # ── 3. Audit chain integrity verification ─────────────────────────────────
    try:
        from src.integrity.audit_chain import run_integrity_check
        integrity_result = await run_integrity_check(store, "loan", application_id)
        integrity_dict = integrity_result.to_dict()
    except Exception as exc:
        integrity_dict = {"error": str(exc), "chain_valid": False}

    # ── 4. Human-readable narrative ───────────────────────────────────────────
    narrative = await _generate_narrative(events, application_id)

    # ── 5. Agent metadata ─────────────────────────────────────────────────────
    agent_metadata = _extract_agent_metadata(events)

    # ── Build package and compute self-verifying hash ─────────────────────────
    package_content = {
        "application_id":    application_id,
        "examination_date":  exam_date_str,
        "generated_at":      generated_at,
        "total_events":      len(events),
        "event_stream":      event_records,
        "projection_states": projection_states,
        "integrity_result":  integrity_dict,
        "narrative":         narrative,
        "agent_metadata":    agent_metadata,
    }
    package_hash = hashlib.sha256(
        json.dumps(package_content, sort_keys=True, default=str).encode()
    ).hexdigest()

    return RegulatoryPackage(
        application_id    = application_id,
        examination_date  = exam_date_str,
        generated_at      = generated_at,
        package_hash      = package_hash,
        event_stream      = event_records,
        projection_states = projection_states,
        integrity_result  = integrity_dict,
        narrative         = narrative,
        agent_metadata    = agent_metadata,
        total_events      = len(events),
    )


async def _generate_narrative(events: list[Any], application_id: str) -> str:
    """
    Generate one-sentence narrative per significant event.
    Uses Gemini if available, falls back to template-based generation.
    """
    narrative_events = [e for e in events if e.event_type in NARRATIVE_EVENTS]

    api_key = os.environ.get("GEMINI_API_KEY")
    if api_key and narrative_events:
        try:
            return await _gemini_narrative(narrative_events, application_id, api_key)
        except Exception as exc:
            logger.warning("Gemini narrative generation failed: %s", exc)

    return _template_narrative(narrative_events, application_id)


async def _gemini_narrative(
    events: list[Any],
    application_id: str,
    api_key: str,
) -> str:
    import google.generativeai as genai
    genai.configure(api_key=api_key)

    event_descriptions = []
    for e in events:
        p = e.payload
        ts = e.recorded_at.isoformat() if e.recorded_at else "unknown time"
        desc = f"{ts}: {e.event_type}"
        if e.event_type == "ApplicationSubmitted":
            desc += f" — applicant {p.get('applicant_id')}, amount ${p.get('requested_amount_usd'):,.0f}"
        elif e.event_type == "CreditAnalysisCompleted":
            decision = p.get("decision", {})
            rt = decision.get("risk_tier", "?") if isinstance(decision, dict) else "?"
            conf = decision.get("confidence", "?") if isinstance(decision, dict) else "?"
            desc += f" — risk_tier={rt}, confidence={conf}, model={p.get('model_version','?')}"
        elif e.event_type == "FraudScreeningCompleted":
            desc += f" — fraud_score={p.get('fraud_score')}, recommendation={p.get('recommendation')}"
        elif e.event_type == "ComplianceRulePassed":
            desc += f" — rule {p.get('rule_id')} PASSED"
        elif e.event_type == "ComplianceRuleFailed":
            desc += f" — rule {p.get('rule_id')} FAILED: {p.get('failure_reason','')}"
        elif e.event_type == "DecisionGenerated":
            desc += f" — recommendation={p.get('recommendation')}, confidence={p.get('confidence')}"
        elif e.event_type == "ApplicationApproved":
            desc += f" — approved ${p.get('approved_amount_usd'):,.0f}"
        elif e.event_type == "ApplicationDeclined":
            desc += f" — reasons: {p.get('decline_reasons', [])}"
        elif e.event_type == "HumanReviewCompleted":
            desc += f" — reviewer={p.get('reviewer_id')}, decision={p.get('final_decision')}, override={p.get('override')}"
        event_descriptions.append(desc)

    prompt = (
        f"You are generating a regulatory examination narrative for loan application {application_id}.\n"
        f"Write exactly one clear, factual sentence per event below. "
        f"Use past tense. Include all key facts (amounts, scores, decisions, model versions). "
        f"Format as a numbered list. This will be read by a bank regulator.\n\n"
        + "\n".join(event_descriptions)
    )

    model    = genai.GenerativeModel("gemini-2.0-flash")
    response = model.generate_content(prompt)
    return response.text


def _template_narrative(events: list[Any], application_id: str) -> str:
    """Template-based narrative fallback when Gemini is unavailable."""
    lines = [f"Regulatory Examination Narrative — Application {application_id}\n"]
    for i, e in enumerate(events, 1):
        p  = e.payload
        ts = e.recorded_at.strftime("%Y-%m-%d %H:%M:%S UTC") if e.recorded_at else "unknown"
        line = f"{i}. [{ts}] "

        if e.event_type == "ApplicationSubmitted":
            line += (f"Application submitted by {p.get('applicant_id')} via "
                     f"{p.get('submission_channel')} for "
                     f"${float(p.get('requested_amount_usd', 0)):,.0f} "
                     f"({p.get('loan_purpose')}).")
        elif e.event_type == "CreditAnalysisCompleted":
            decision = p.get("decision", {})
            rt   = decision.get("risk_tier", "?") if isinstance(decision, dict) else "?"
            conf = decision.get("confidence", "?") if isinstance(decision, dict) else "?"
            line += (f"Credit analysis completed by model {p.get('model_version','?')}: "
                     f"risk_tier={rt}, confidence={conf}, "
                     f"input_hash={p.get('input_data_hash','?')[:8]}.")
        elif e.event_type == "FraudScreeningCompleted":
            line += (f"Fraud screening completed: score={p.get('fraud_score')}, "
                     f"risk={p.get('risk_level')}, recommendation={p.get('recommendation')}.")
        elif e.event_type == "ComplianceRulePassed":
            line += f"Compliance rule {p.get('rule_id')} ({p.get('rule_name')}) passed."
        elif e.event_type == "ComplianceRuleFailed":
            line += (f"Compliance rule {p.get('rule_id')} ({p.get('rule_name')}) FAILED: "
                     f"{p.get('failure_reason')}. Hard block: {p.get('is_hard_block')}.")
        elif e.event_type == "DecisionGenerated":
            line += (f"AI orchestrator generated decision: {p.get('recommendation')} "
                     f"(confidence={p.get('confidence')}).")
        elif e.event_type == "ApplicationApproved":
            line += (f"Application approved for ${float(p.get('approved_amount_usd', 0)):,.0f} "
                     f"by {p.get('approved_by')}.")
        elif e.event_type == "ApplicationDeclined":
            line += f"Application declined by {p.get('declined_by')}."
        elif e.event_type == "HumanReviewCompleted":
            line += (f"Human review by {p.get('reviewer_id')}: "
                     f"decision={p.get('final_decision')}, override={p.get('override')}.")
        elif e.event_type == "AuditIntegrityCheckRun":
            line += (f"Integrity check: {p.get('events_verified_count')} events verified, "
                     f"chain_valid={p.get('chain_valid')}, tamper={p.get('tamper_detected')}.")
        else:
            line += f"{e.event_type}."

        lines.append(line)

    return "\n".join(lines)


def _extract_agent_metadata(events: list[Any]) -> list[dict[str, Any]]:
    """Extract all AI agent participation metadata from the event stream."""
    agents: dict[str, dict[str, Any]] = {}

    for e in events:
        p = e.payload
        session_id = p.get("session_id")
        if not session_id:
            continue

        if session_id not in agents:
            agents[session_id] = {
                "session_id":    session_id,
                "model_version": None,
                "confidence":    None,
                "input_data_hash": None,
                "analysis_type": None,
                "participated_at": None,
            }

        if e.event_type == "AgentSessionStarted":
            agents[session_id]["model_version"]   = p.get("model_version")
            agents[session_id]["participated_at"]  = e.recorded_at.isoformat() if e.recorded_at else None

        elif e.event_type == "CreditAnalysisCompleted":
            decision = p.get("decision", {})
            agents[session_id]["confidence"]      = (decision.get("confidence")
                                                     if isinstance(decision, dict) else None)
            agents[session_id]["input_data_hash"] = p.get("input_data_hash")
            agents[session_id]["analysis_type"]   = "credit_analysis"
            if not agents[session_id]["model_version"]:
                agents[session_id]["model_version"] = p.get("model_version")

        elif e.event_type == "FraudScreeningCompleted":
            agents[session_id]["input_data_hash"] = p.get("input_data_hash")
            agents[session_id]["analysis_type"]   = "fraud_screening"

        elif e.event_type == "DecisionGenerated":
            model_versions = p.get("model_versions", {})
            if isinstance(model_versions, dict):
                agents[session_id]["model_version"] = model_versions.get(
                    session_id, agents[session_id].get("model_version")
                )
            agents[session_id]["analysis_type"] = "decision_orchestrator"
            agents[session_id]["confidence"]    = p.get("confidence")

    return list(agents.values())
