"""
src/integrity/gas_town.py

Phase 4C: Full Gas Town agent memory reconstruction with token budget,
NEEDS_RECONCILIATION detection, and Gemini-powered prose summarisation.

An agent that crashes mid-session calls reconstruct_agent_context() on restart.
It receives an AgentContext with:
  - A token-efficient prose summary of old events (generated by Gemini)
  - Verbatim last 3 events (always preserved — recency matters most)
  - Any PENDING or partial-decision events preserved verbatim
  - NEEDS_RECONCILIATION flag if the last event was a partial decision

The prose summarisation uses Google Gemini (gemini-2.0-flash) so the
context text fits within the agent's token budget even for long sessions.
If the Gemini API is unavailable, falls back to a structured text summary.

Usage:
    ctx = await reconstruct_agent_context(store, "credit_analysis", "sess-cre-abc123")
    if ctx.session_health_status == "NEEDS_RECONCILIATION":
        # resolve partial state before continuing
    print(ctx.context_text)
"""
from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

logger = logging.getLogger(__name__)

# Events that indicate a decision was started but not completed
PARTIAL_DECISION_STARTERS = {
    "CreditAnalysisRequested",
    "FraudScreeningRequested",
    "ComplianceCheckRequested",
    "DecisionRequested",
}
PARTIAL_DECISION_COMPLETERS = {
    "CreditAnalysisCompleted",
    "FraudScreeningCompleted",
    "ComplianceCheckCompleted",
    "DecisionGenerated",
}

VERBATIM_PRESERVE_COUNT = 3   # always keep last N events verbatim


@dataclass
class AgentContext:
    session_id:           str
    agent_type:           str
    application_id:       str | None
    model_version:        str | None
    context_text:         str
    last_event_position:  int
    pending_work:         list[str]
    session_health_status: str        # OK | NEEDS_RECONCILIATION | CRASHED
    total_events:         int
    summarised_events:    int
    verbatim_events:      int


async def reconstruct_agent_context(
    store: Any,
    agent_type: str,
    session_id: str,
    token_budget: int = 8000,
) -> AgentContext:
    """
    Reconstruct agent context from event stream after a crash.

    1. Load full AgentSession stream
    2. Identify pending work and partial decisions
    3. Preserve verbatim: last 3 events + any PENDING/partial events
    4. Summarise older events into token-efficient prose via Gemini
    5. Return AgentContext with health status
    """
    stream_id = f"agent-{agent_type}-{session_id}"
    events    = await store.load_stream(stream_id)

    if not events:
        return AgentContext(
            session_id            = session_id,
            agent_type            = agent_type,
            application_id        = None,
            model_version         = None,
            context_text          = "No events found for this session.",
            last_event_position   = 0,
            pending_work          = [],
            session_health_status = "CRASHED",
            total_events          = 0,
            summarised_events     = 0,
            verbatim_events       = 0,
        )

    # ── Extract session metadata from AgentSessionStarted ─────────────────────
    session_start = next(
        (e for e in events if e.event_type == "AgentSessionStarted"), None
    )
    application_id = session_start.payload.get("application_id") if session_start else None
    model_version  = session_start.payload.get("model_version")  if session_start else None

    # ── Identify partial decisions (NEEDS_RECONCILIATION) ─────────────────────
    pending_work: list[str] = []
    for i, event in enumerate(events):
        if event.event_type in PARTIAL_DECISION_STARTERS:
            # Check if a corresponding completer follows
            completer_present = any(
                e.event_type in PARTIAL_DECISION_COMPLETERS
                for e in events[i+1:]
            )
            if not completer_present:
                pending_work.append(
                    f"{event.event_type} at position {event.stream_position} "
                    f"(no completion event found)"
                )

    session_health = "NEEDS_RECONCILIATION" if pending_work else "OK"

    # ── Split events: verbatim (recent) vs. to-summarise (older) ──────────────
    verbatim_events   = events[-VERBATIM_PRESERVE_COUNT:]
    events_to_summarise = events[:-VERBATIM_PRESERVE_COUNT] if len(events) > VERBATIM_PRESERVE_COUNT else []

    # Always add any partial-decision events to verbatim regardless of position
    partial_positions = {int(pw.split("position ")[1].split(" ")[0])
                         for pw in pending_work if "position" in pw}
    additional_verbatim = [e for e in events_to_summarise
                           if e.stream_position in partial_positions]
    events_to_summarise = [e for e in events_to_summarise
                           if e.stream_position not in partial_positions]

    # ── Generate prose summary ─────────────────────────────────────────────────
    if events_to_summarise:
        summary_text = await _summarise_with_gemini(
            events_to_summarise, agent_type, application_id, token_budget
        )
    else:
        summary_text = ""

    # ── Build verbatim section ─────────────────────────────────────────────────
    all_verbatim = additional_verbatim + verbatim_events
    verbatim_text = _format_verbatim(all_verbatim)

    # ── Assemble final context text ────────────────────────────────────────────
    parts = []
    parts.append(
        f"=== AGENT SESSION RECONSTRUCTION ===\n"
        f"Agent:       {agent_type}\n"
        f"Session:     {session_id}\n"
        f"Application: {application_id or 'unknown'}\n"
        f"Model:       {model_version or 'unknown'}\n"
        f"Status:      {session_health}\n"
        f"Events:      {len(events)} total\n"
    )

    if pending_work:
        parts.append("\n=== PENDING WORK (requires reconciliation) ===\n")
        parts.extend(f"- {w}\n" for w in pending_work)

    if summary_text:
        parts.append(f"\n=== PRIOR SESSION HISTORY (summarised) ===\n{summary_text}\n")

    if verbatim_text:
        parts.append(f"\n=== RECENT EVENTS (verbatim) ===\n{verbatim_text}\n")

    context_text = "".join(parts)

    return AgentContext(
        session_id            = session_id,
        agent_type            = agent_type,
        application_id        = application_id,
        model_version         = model_version,
        context_text          = context_text,
        last_event_position   = events[-1].stream_position,
        pending_work          = pending_work,
        session_health_status = session_health,
        total_events          = len(events),
        summarised_events     = len(events_to_summarise),
        verbatim_events       = len(all_verbatim),
    )


async def _summarise_with_gemini(
    events: list[Any],
    agent_type: str,
    application_id: str | None,
    token_budget: int,
) -> str:
    """
    Use Gemini to produce a token-efficient prose summary of older session events.
    Falls back to structured text if the API key is not set or the call fails.
    """
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        logger.info("GEMINI_API_KEY not set — using structured text fallback")
        return _structured_summary_fallback(events, agent_type, application_id)

    try:
        import google.generativeai as genai
        genai.configure(api_key=api_key)

        event_descriptions = []
        for e in events:
            p = e.payload
            desc = f"[pos={e.stream_position}] {e.event_type}"
            # Add key fields per event type
            if e.event_type == "AgentSessionStarted":
                desc += f" model={p.get('model_version', '?')} source={p.get('context_source', '?')}"
            elif e.event_type == "AgentNodeExecuted":
                desc += f" node={p.get('node_name', '?')} llm={p.get('llm_called', False)}"
            elif e.event_type == "AgentToolCalled":
                desc += f" tool={p.get('tool_name', '?')}"
            elif e.event_type == "CreditAnalysisCompleted":
                decision = p.get("decision", {})
                desc += (f" risk={decision.get('risk_tier','?') if isinstance(decision,dict) else '?'}"
                         f" confidence={decision.get('confidence','?') if isinstance(decision,dict) else '?'}")
            event_descriptions.append(desc)

        prompt = (
            f"You are reconstructing context for an AI agent that crashed mid-session.\n"
            f"Agent type: {agent_type}\n"
            f"Application: {application_id or 'unknown'}\n\n"
            f"Summarise the following session events in plain English. "
            f"Be concise — target under 400 words. Focus on: what work was completed, "
            f"what decisions were made, what data was processed. "
            f"Use past tense. Do not include raw JSON.\n\n"
            f"Events:\n" + "\n".join(event_descriptions)
        )

        model    = genai.GenerativeModel("gemini-2.0-flash")
        response = model.generate_content(prompt)
        return response.text

    except Exception as exc:
        logger.warning("Gemini summarisation failed (%s) — using fallback", exc)
        return _structured_summary_fallback(events, agent_type, application_id)


def _structured_summary_fallback(
    events: list[Any],
    agent_type: str,
    application_id: str | None,
) -> str:
    """Plain text fallback when Gemini is unavailable."""
    lines = [f"Session history for {agent_type} on {application_id or 'unknown'}:\n"]
    for e in events:
        p    = e.payload
        line = f"  [{e.stream_position:3d}] {e.event_type}"
        if e.event_type == "AgentNodeExecuted":
            line += f" — {p.get('node_name', '')}"
        elif e.event_type == "AgentToolCalled":
            line += f" — {p.get('tool_name', '')}"
        elif e.event_type == "CreditAnalysisCompleted":
            decision = p.get("decision", {})
            rt = decision.get("risk_tier", "?") if isinstance(decision, dict) else "?"
            line += f" — risk_tier={rt}"
        lines.append(line)
    return "\n".join(lines)


def _format_verbatim(events: list[Any]) -> str:
    """Format events for verbatim inclusion in context."""
    lines = []
    for e in events:
        lines.append(
            f"[pos={e.stream_position}] {e.event_type} @ {e.recorded_at.isoformat()}\n"
            f"  {json.dumps(e.payload, default=str, indent=2)}\n"
        )
    return "\n".join(lines)