#!/usr/bin/env python3
"""
scripts/load_seed_data.py

Loads a seed_events.jsonl file (generated by your synthetic data pipeline)
into any target PostgreSQL database.

The loader:
  1. Reads events in JSONL order (preserving global_position ordering)
  2. Groups consecutive events by stream_id to build stream state
  3. Upserts event_streams rows (idempotent — safe to re-run)
  4. Inserts events — skips if (stream_id, stream_position) already exists
  5. Writes outbox rows alongside events (same transaction per batch)

JSONL format (matches seed_events.jsonl):
  {"stream_id": "...", "event_type": "...", "event_version": 1,
   "payload": {...}, "recorded_at": "2026-02-24T07:37:29.767699"}

Usage:
  # Load into dev database
  python scripts/load_seed_data.py data/seed_events.jsonl

  # Load into test database
  python scripts/load_seed_data.py data/seed_events.jsonl --db-url postgresql://ledger:ledger_dev_secret@localhost:5433/ledger_test

  # Dry run (validate only, no writes)
  python scripts/load_seed_data.py data/seed_events.jsonl --dry-run

  # Override duplicate handling
  python scripts/load_seed_data.py data/seed_events.jsonl --on-conflict skip
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
import uuid
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

import asyncpg
from dotenv import load_dotenv

load_dotenv()

# ── stream prefix → aggregate_type ────────────────────────────────────────────
AGGREGATE_TYPE_MAP = {
    "loan":       "LoanApplication",
    "docpkg":     "DocumentPackage",
    "agent":      "AgentSession",
    "credit":     "CreditRecord",
    "fraud":      "FraudRecord",
    "compliance": "ComplianceRecord",
}


def infer_aggregate_type(stream_id: str) -> str:
    prefix = stream_id.split("-")[0]
    return AGGREGATE_TYPE_MAP.get(prefix, "Unknown")


# =============================================================================
# Core loader
# =============================================================================

async def load_seed_data(
    jsonl_path: Path,
    db_url: str,
    dry_run: bool = False,
    on_conflict: str = "skip",         # "skip" | "error"
    batch_size: int = 100,
    verbose: bool = True,
) -> dict[str, int]:
    """
    Load all events from jsonl_path into the target database.

    Returns stats dict: {total_read, inserted, skipped, streams_created}.
    """
    # ── Read and validate ──────────────────────────────────────────────────────
    raw_events: list[dict] = []
    with jsonl_path.open() as f:
        for lineno, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                evt = json.loads(line)
            except json.JSONDecodeError as e:
                print(f"ERROR: line {lineno} is not valid JSON: {e}", file=sys.stderr)
                sys.exit(1)
            for field in ("stream_id", "event_type", "event_version", "payload", "recorded_at"):
                if field not in evt:
                    print(f"ERROR: line {lineno} missing required field '{field}'", file=sys.stderr)
                    sys.exit(1)
            raw_events.append(evt)

    if verbose:
        print(f"✓ Read {len(raw_events)} events from {jsonl_path}")

    if dry_run:
        # Validate and summarise without writing
        stream_counts: dict[str, int] = defaultdict(int)
        type_counts:   dict[str, int] = defaultdict(int)
        for e in raw_events:
            stream_counts[e["stream_id"]] += 1
            type_counts[e["event_type"]] += 1
        print(f"\n  DRY RUN — would insert {len(raw_events)} events")
        print(f"  Unique streams:      {len(stream_counts)}")
        print(f"  Unique event types:  {len(type_counts)}")
        print("\n  Top 10 event types:")
        for etype, count in sorted(type_counts.items(), key=lambda x: -x[1])[:10]:
            print(f"    {count:4d}  {etype}")
        return {"total_read": len(raw_events), "inserted": 0, "skipped": 0, "streams_created": 0}

    # ── Build per-stream position map (1-based) ────────────────────────────────
    stream_positions: dict[str, int] = defaultdict(int)
    enriched: list[dict] = []
    for evt in raw_events:
        sid = evt["stream_id"]
        stream_positions[sid] += 1
        enriched.append({**evt, "_position": stream_positions[sid]})

    # ── Connect and load ───────────────────────────────────────────────────────
    pool = await asyncpg.create_pool(dsn=db_url, min_size=2, max_size=5)
    stats = {"total_read": len(enriched), "inserted": 0, "skipped": 0, "streams_created": 0}

    try:
        # Upsert event_streams rows
        unique_streams = {e["stream_id"] for e in enriched}
        async with pool.acquire() as conn:
            for sid in unique_streams:
                atype = infer_aggregate_type(sid)
                result = await conn.execute(
                    """
                    INSERT INTO event_streams (stream_id, aggregate_type, current_version)
                    VALUES ($1, $2, $3)
                    ON CONFLICT (stream_id) DO NOTHING
                    """,
                    sid, atype, stream_positions[sid],
                )
                if result == "INSERT 1":
                    stats["streams_created"] += 1
                else:
                    # Update version if existing stream has lower version
                    await conn.execute(
                        """
                        UPDATE event_streams
                        SET    current_version = GREATEST(current_version, $2)
                        WHERE  stream_id = $1
                        """,
                        sid, stream_positions[sid],
                    )

        # Insert events in batches
        for batch_start in range(0, len(enriched), batch_size):
            batch = enriched[batch_start: batch_start + batch_size]
            async with pool.acquire() as conn:
                async with conn.transaction():
                    for evt in batch:
                        payload_json = json.dumps(evt["payload"])
                        recorded_at  = datetime.fromisoformat(evt["recorded_at"].replace("Z", "+00:00"))
                        eid          = uuid.uuid4()

                        if on_conflict == "skip":
                            result = await conn.execute(
                                """
                                INSERT INTO events
                                  (event_id, stream_id, stream_position,
                                   event_type, event_version, payload, metadata, recorded_at)
                                VALUES ($1, $2, $3, $4, $5, $6::jsonb, '{}'::jsonb, $7)
                                ON CONFLICT (stream_id, stream_position) DO NOTHING
                                """,
                                eid,
                                evt["stream_id"],
                                evt["_position"],
                                evt["event_type"],
                                evt["event_version"],
                                payload_json,
                                recorded_at,
                            )
                            if result == "INSERT 0":
                                stats["skipped"] += 1
                                continue
                        else:
                            await conn.execute(
                                """
                                INSERT INTO events
                                  (event_id, stream_id, stream_position,
                                   event_type, event_version, payload, metadata, recorded_at)
                                VALUES ($1, $2, $3, $4, $5, $6::jsonb, '{}'::jsonb, $7)
                                """,
                                eid,
                                evt["stream_id"],
                                evt["_position"],
                                evt["event_type"],
                                evt["event_version"],
                                payload_json,
                                recorded_at,
                            )

                        stats["inserted"] += 1

                        # Write outbox row alongside
                        outbox_payload = {
                            **evt["payload"],
                            "stream_id":  evt["stream_id"],
                            "event_type": evt["event_type"],
                        }
                        await conn.execute(
                            """
                            INSERT INTO outbox (event_id, destination, payload)
                            VALUES ($1, 'seed-loader', $2::jsonb)
                            ON CONFLICT DO NOTHING
                            """,
                            eid, json.dumps(outbox_payload),
                        )

            if verbose:
                pct = (batch_start + len(batch)) / len(enriched) * 100
                print(f"  Loaded {batch_start + len(batch):5d}/{len(enriched)} "
                      f"({pct:5.1f}%)  inserted={stats['inserted']}  skipped={stats['skipped']}")

    finally:
        await pool.close()

    return stats


# =============================================================================
# CLI entrypoint
# =============================================================================

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Load synthetic seed events into a PostgreSQL ledger database"
    )
    parser.add_argument("jsonl_path", type=Path, help="Path to seed_events.jsonl")
    parser.add_argument(
        "--db-url",
        default=os.environ.get("DATABASE_URL", "postgresql://ledger:ledger_dev_secret@localhost:5432/ledger"),
        help="asyncpg connection string (default: $DATABASE_URL env var)"
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Validate and print stats without writing to the database"
    )
    parser.add_argument(
        "--on-conflict", choices=["skip", "error"], default="skip",
        help="What to do when (stream_id, stream_position) already exists"
    )
    parser.add_argument(
        "--batch-size", type=int, default=100,
        help="Events per transaction batch (default: 100)"
    )
    parser.add_argument("--quiet", action="store_true", help="Suppress progress output")
    args = parser.parse_args()

    if not args.jsonl_path.exists():
        print(f"ERROR: file not found: {args.jsonl_path}", file=sys.stderr)
        sys.exit(1)

    stats = asyncio.run(
        load_seed_data(
            jsonl_path  = args.jsonl_path,
            db_url      = args.db_url,
            dry_run     = args.dry_run,
            on_conflict = args.on_conflict,
            batch_size  = args.batch_size,
            verbose     = not args.quiet,
        )
    )

    print()
    print("─" * 50)
    print("Seed load complete")
    print(f"  Total events read : {stats['total_read']}")
    print(f"  Inserted          : {stats['inserted']}")
    print(f"  Skipped (dup)     : {stats['skipped']}")
    print(f"  Streams created   : {stats['streams_created']}")


if __name__ == "__main__":
    main()
